___
- FileName: 20201124-list.append时遇到的bug.md
- Author: ihuangch -huangch96@qq.com
- Description: ---
- Create:2020-11-24 18:45:49
___

```python
def gen_data_disks(instance_data_disk_size):
    disk_list = []
    disk_spec = {
    'diskCategory': 'cloud',
    'CloudDiskSpec': {
    'DiskType': 'ssd',
     }
     }
    for i in range(0, len(instance_data_disk_size)):
        disk_spec['CloudDiskSpec']['DiskSizeGB'] = instance_data_disk_size[i]
        print(disk_spec)
        print(id(disk_spec))
        disk_list.append(disk_spec)
    return disk_list
```

```python
def gen_data_disks(instance_data_disk_size):
    disk_list = []
    for i in range(0, len(instance_data_disk_size)):
        disk_spec = {
            'diskCategory': 'cloud',
            'CloudDiskSpec': {
                'DiskType': 'ssd',
                'DiskSizeGB': instance_data_disk_size[i]
             }
        }
        print(disk_spec)
        print(id(disk_spec))
        print(id(i))
        disk_list.append(disk_spec)
    return disk_list
```